package dto

const AnomalyFilterType = "Anomaly"

const (
	FieldIdentifierCluster         = "CLUSTER"
	FieldIdentifierAWS             = "AWS"
	FieldIdentifierGCP             = "GCP"
	FieldIdentifierAzure           = "AZURE"
	FieldIdentifierExternalData    = "EXTERNAL_DATA"
	FieldIdentifierCommon          = "COMMON"
	FieldIdentifierCustom          = "CUSTOM"
	FieldIdentifierBusinessMapping = "BUSINESS_MAPPING"
	FieldIdentifierLabel           = "LABEL"
	FieldIdentifierLabelV2         = "LABEL_V2"
)

const (
	TimeFilterOperatorNotIn               = "NOT_IN"
	TimeFilterOperatorIn                  = "IN"
	TimeFilterOperatorEquals              = "EQUALS"
	TimeFilterOperatorNotNull             = "NOT_NULL"
	TimeFilterOperatorNull                = "NULL"
	TimeFilterOperatorLike                = "LIKE"
	TimeFilterOperatorGreaterThan         = "GREATER_THAN"
	TimeFilterOperatorLessThan            = "LESS_THAN"
	TimeFilterOperatorGreaterThanEqualsTo = "GREATER_THAN_EQUALS_TO"
	TimeFilterOperatorLessThanEqualsTo    = "LESS_THAN_EQUALS_TO"
	TimeFilterOperatorAfter               = "AFTER"
	TimeFilterOperatorBefore              = "BEFORE"
)

const (
	TimeRangeLastMonth    = "LAST_MONTH"
	TimeRangeCurrentMonth = "CURRENT_MONTH"
)

const (
	AnomTimeGroupByHour    = "HOUR"
	AnomTimeGroupByDay     = "DAY"
	AnomTimeGroupByMonth   = "MONTH"
	AnomTimeGroupByWeek    = "WEEK"
	AnomTimeGroupByQuarter = "QUARTER"
	AnomTimeGroupByYear    = "YEAR"
)

const (
	AnomFilterOperatorNotIn   = "NOT_IN"
	AnomFilterOperatorIn      = "IN"
	AnomFilterOperatorEquals  = "EQUALS"
	AnomFilterOperatorNotNull = "NOT_NULL"
	AnomFilterOperatorNull    = "NULL"
	AnomFilterOperatorLike    = "LIKE"
	AnomFilterOperatorSearch  = "SEARCH"
)

const (
	AgregOperationTypeSum   = "SUM"
	AgregOperationTypeMax   = "MAX"
	AgregOperationTypeMin   = "MIN"
	AgregOperationTypeAvg   = "AVG"
	AgregOperationTypeCount = "COUNT"
)

const (
	AnomalyStatusActive   = "ACTIVE"
	AnomalyStatusIgnored  = "IGNORED"
	AnomalyStatusArchived = "ARCHIVED"
	AnomalyStatusResolved = "RESOLVED"
)

const (
	AnomalyFieldPerspectiveID           = "PERSPECTIVE_ID"
	AnomalyFieldAnomalyID               = "ANOMALY_ID"
	AnomalyFieldWorkload                = "WORKLOAD"
	AnomalyFieldWorkloadType            = "WORKLOAD_TYPE"
	AnomalyFieldClusterID               = "CLUSTER_ID"
	AnomalyFieldClusterName             = "CLUSTER_NAME"
	AnomalyFieldClusterNamespace        = "CLUSTER_NAMESPACE"
	AnomalyFieldClusterNamespaceID      = "CLUSTER_NAMESPACE_ID"
	AnomalyFieldClusterWorkload         = "CLUSTER_WORKLOAD"
	AnomalyFieldClusterWorkloadID       = "CLUSTER_WORKLOAD_ID"
	AnomalyFieldClusterNode             = "CLUSTER_NODE"
	AnomalyFieldClusterPod              = "CLUSTER_POD"
	AnomalyFieldClusterParentInstanceID = "CLUSTER_PARENT_INSTANCE_ID"
	AnomalyFieldClusterStorage          = "CLUSTER_STORAGE"
	AnomalyFieldClusterApplication      = "CLUSTER_APPLICATION"
	AnomalyFieldClusterEnvironment      = "CLUSTER_ENVIRONMENT"
	AnomalyFieldClusterService          = "CLUSTER_SERVICE"
	AnomalyFieldClusterCloudProvider    = "CLUSTER_CLOUD_PROVIDER"
	AnomalyFieldClusterEcsService       = "CLUSTER_ECS_SERVICE"
	AnomalyFieldClusterEcsServiceID     = "CLUSTER_ECS_SERVICE_ID"
	AnomalyFieldClusterEcsTask          = "CLUSTER_ECS_TASK"
	AnomalyFieldClusterEcsTaskID        = "CLUSTER_ECS_TASK_ID"
	AnomalyFieldClusterEcsLaunchType    = "CLUSTER_ECS_LAUNCH_TYPE"
	AnomalyFieldClusterEcsLaunchTypeID  = "CLUSTER_ECS_LAUNCH_TYPE_ID"
	AnomalyFieldNamespace               = "NAMESPACE"
	AnomalyFieldService                 = "SERVICE"
	AnomalyFieldServiceName             = "SERVICE_NAME"
	AnomalyFieldGcpProduct              = "GCP_PRODUCT"
	AnomalyFieldGcpProject              = "GCP_PROJECT"
	AnomalyFieldGcpSkuID                = "GCP_SKU_ID"
	AnomalyFieldGcpSkuDescription       = "GCP_SKU_DESCRIPTION"
	AnomalyFieldAwsAccount              = "AWS_ACCOUNT"
	AnomalyFieldAwsService              = "AWS_SERVICE"
	AnomalyFieldAwsInstanceType         = "AWS_INSTANCE_TYPE"
	AnomalyFieldAwsUsageType            = "AWS_USAGE_TYPE"
	AnomalyFieldAwsBillingEntity        = "AWS_BILLING_ENTITY"
	AnomalyFieldAwsLineItemType         = "AWS_LINE_ITEM_TYPE"
	AnomalyFieldAzureSubscriptionGuid   = "AZURE_SUBSCRIPTION_GUID"
	AnomalyFieldAzureMeterName          = "AZURE_METER_NAME"
	AnomalyFieldAzureMeterCategory      = "AZURE_METER_CATEGORY"
	AnomalyFieldAzureMeterSubcategory   = "AZURE_METER_SUBCATEGORY"
	AnomalyFieldAzureResourceID         = "AZURE_RESOURCE_ID"
	AnomalyFieldAzureResourceGroupName  = "AZURE_RESOURCE_GROUP_NAME"
	AnomalyFieldAzureResourceType       = "AZURE_RESOURCE_TYPE"
	AnomalyFieldAzureResource           = "AZURE_RESOURCE"
	AnomalyFieldAzureServiceName        = "AZURE_SERVICE_NAME"
	AnomalyFieldAzureServiceTier        = "AZURE_SERVICE_TIER"
	AnomalyFieldAzureInstanceID         = "AZURE_INSTANCE_ID"
	AnomalyFieldAzureSubscriptionName   = "AZURE_SUBSCRIPTION_NAME"
	AnomalyFieldAzurePublisherName      = "AZURE_PUBLISHER_NAME"
	AnomalyFieldAzurePublisherType      = "AZURE_PUBLISHER_TYPE"
	AnomalyFieldAzureReservationID      = "AZURE_RESERVATION_ID"
	AnomalyFieldAzureReservationName    = "AZURE_RESERVATION_NAME"
	AnomalyFieldAzureFrequency          = "AZURE_FREQUENCY"
	AnomalyFieldAzureChargeType         = "AZURE_CHARGE_TYPE"
	AnomalyFieldAzurePricingModel       = "AZURE_PRICING_MODEL"
	AnomalyFieldAzureBenefitName        = "AZURE_BENEFIT_NAME"
	AnomalyFieldAzureResourceName       = "AZURE_RESOURCE_NAME"
	AnomalyFieldCommonProduct           = "COMMON_PRODUCT"
	AnomalyFieldCommonRegion            = "COMMON_REGION"
	AnomalyFieldCommonNone              = "COMMON_NONE"
	AnomalyFieldCloudProvider           = "CLOUD_PROVIDER"
	AnomalyFieldStatus                  = "STATUS"
	AnomalyFieldRegion                  = "REGION"
	AnomalyFieldAnomalyTime             = "ANOMALY_TIME"
	AnomalyFieldActualCost              = "ACTUAL_COST"
	AnomalyFieldExpectedCost            = "EXPECTED_COST"
	AnomalyFieldAnomalousSpend          = "ANOMALOUS_SPEND"
	AnomalyFieldCostImpact              = "COST_IMPACT"
	AnomalyFieldAll                     = "ALL"
	AnomalyFieldAnomalousSpendPercent   = "ANOMALOUS_SPEND_PERCENTAGE"
	AnomalyFieldTotalCost               = "TOTAL_COST"
	AnomalyFieldIdleCost                = "IDLE_COST"
	AnomalyFieldUnallocatedCost         = "UNALLOCATED_COST"
	AnomalyFieldRuleName                = "RULE_NAME"
	AnomalyFieldRuleSetName             = "RULE_SET_NAME"
	AnomalyFieldPotentialSavings        = "POTENTIAL_SAVINGS"
	AnomalyFieldLastEvaluatedAt         = "LAST_EVALUATED_AT"
	AnomalyFieldAnomalyStatus           = "ANOMALY_STATUS"
	AnomalyFieldRecommendationsCount    = "RECOMMENDATIONS_COUNT"
	AnomalyFieldActualAmount            = "ACTUAL_AMOUNT"
	AnomalyFieldCriticality             = "CRITICALITY"
	AnomalyFieldDuration                = "DURATION"
	AnomalyFieldUpdatedAt               = "UPDATED_AT"
	AnomalyFieldUpdatedBy               = "UPDATED_BY"
	AnomalyFieldUpdatedAtRelative       = "UPDATED_AT_RELATIVE"
)
