[package]
name = "harness-mcp-config"
version = "0.1.0"
edition = "2021"
description = "Configuration management for Harness MCP Server"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
config = "0.14"
anyhow = "1.0"
thiserror = "1.0"