// Package ar provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package ar

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ArtifactType.
const (
	ArtifactTypeDataset ArtifactType = "dataset"
	ArtifactTypeModel   ArtifactType = "model"
)

// Defines values for ArtifactVersionMetadataFirewallMode.
const (
	ArtifactVersionMetadataFirewallModeALLOW ArtifactVersionMetadataFirewallMode = "ALLOW"
	ArtifactVersionMetadataFirewallModeBLOCK ArtifactVersionMetadataFirewallMode = "BLOCK"
	ArtifactVersionMetadataFirewallModeWARN  ArtifactVersionMetadataFirewallMode = "WARN"
)

// Defines values for ArtifactVersionMetadataScanStatus.
const (
	ArtifactVersionMetadataScanStatusALLOWED ArtifactVersionMetadataScanStatus = "ALLOWED"
	ArtifactVersionMetadataScanStatusBLOCKED ArtifactVersionMetadataScanStatus = "BLOCKED"
	ArtifactVersionMetadataScanStatusWARN    ArtifactVersionMetadataScanStatus = "WARN"
)

// Defines values for AuthType.
const (
	AuthTypeAccessKeySecretKey AuthType = "AccessKeySecretKey"
	AuthTypeAnonymous          AuthType = "Anonymous"
	AuthTypeUserPassword       AuthType = "UserPassword"
)

// Defines values for PackageType.
const (
	CARGO       PackageType = "CARGO"
	COMPOSER    PackageType = "COMPOSER"
	CONDA       PackageType = "CONDA"
	DART        PackageType = "DART"
	DOCKER      PackageType = "DOCKER"
	GENERIC     PackageType = "GENERIC"
	GO          PackageType = "GO"
	HELM        PackageType = "HELM"
	HUGGINGFACE PackageType = "HUGGINGFACE"
	MAVEN       PackageType = "MAVEN"
	NPM         PackageType = "NPM"
	NUGET       PackageType = "NUGET"
	PYTHON      PackageType = "PYTHON"
	RAW         PackageType = "RAW"
	RPM         PackageType = "RPM"
	SWIFT       PackageType = "SWIFT"
)

// Defines values for RegistryType.
const (
	RegistryTypeUPSTREAM RegistryType = "UPSTREAM"
	RegistryTypeVIRTUAL  RegistryType = "VIRTUAL"
)

// Defines values for ScannerName.
const (
	AQUATRIVY ScannerName = "AQUA_TRIVY"
	GRYPE     ScannerName = "GRYPE"
)

// Defines values for Status.
const (
	ERROR   Status = "ERROR"
	FAILURE Status = "FAILURE"
	SUCCESS Status = "SUCCESS"
)

// Defines values for UpstreamConfigSource.
const (
	Anaconda     UpstreamConfigSource = "Anaconda"
	AwsEcr       UpstreamConfigSource = "AwsEcr"
	Crates       UpstreamConfigSource = "Crates"
	Custom       UpstreamConfigSource = "Custom"
	Dockerhub    UpstreamConfigSource = "Dockerhub"
	GoProxy      UpstreamConfigSource = "GoProxy"
	HuggingFace  UpstreamConfigSource = "HuggingFace"
	MavenCentral UpstreamConfigSource = "MavenCentral"
	NpmJs        UpstreamConfigSource = "NpmJs"
	NugetOrg     UpstreamConfigSource = "NugetOrg"
	Packagist    UpstreamConfigSource = "Packagist"
	Pubdev       UpstreamConfigSource = "Pubdev"
	PyPi         UpstreamConfigSource = "PyPi"
)

// Defines values for UpstreamProxyConfigFirewallMode.
const (
	ALLOW UpstreamProxyConfigFirewallMode = "ALLOW"
	BLOCK UpstreamProxyConfigFirewallMode = "BLOCK"
	WARN  UpstreamProxyConfigFirewallMode = "WARN"
)

// Defines values for RegistryTypeParam.
const (
	RegistryTypeParamUPSTREAM RegistryTypeParam = "UPSTREAM"
	RegistryTypeParamVIRTUAL  RegistryTypeParam = "VIRTUAL"
)

// Defines values for ArtifactTypeParam.
const (
	ArtifactTypeParamDataset ArtifactTypeParam = "dataset"
	ArtifactTypeParamModel   ArtifactTypeParam = "model"
)

// Defines values for ScopeParam.
const (
	ScopeParamAncestors   ScopeParam = "ancestors"
	ScopeParamDescendants ScopeParam = "descendants"
	ScopeParamNone        ScopeParam = "none"
)

// Defines values for GetArtifactFilesParamsArtifactType.
const (
	GetArtifactFilesParamsArtifactTypeDataset GetArtifactFilesParamsArtifactType = "dataset"
	GetArtifactFilesParamsArtifactTypeModel   GetArtifactFilesParamsArtifactType = "model"
)

// Defines values for GetAllArtifactVersionsParamsArtifactType.
const (
	GetAllArtifactVersionsParamsArtifactTypeDataset GetAllArtifactVersionsParamsArtifactType = "dataset"
	GetAllArtifactVersionsParamsArtifactTypeModel   GetAllArtifactVersionsParamsArtifactType = "model"
)

// Defines values for GetAllArtifactsByRegistryParamsArtifactType.
const (
	Dataset GetAllArtifactsByRegistryParamsArtifactType = "dataset"
	Model   GetAllArtifactsByRegistryParamsArtifactType = "model"
)

// Defines values for GetAllRegistriesParamsType.
const (
	UPSTREAM GetAllRegistriesParamsType = "UPSTREAM"
	VIRTUAL  GetAllRegistriesParamsType = "VIRTUAL"
)

// Defines values for GetAllRegistriesParamsScope.
const (
	GetAllRegistriesParamsScopeAncestors   GetAllRegistriesParamsScope = "ancestors"
	GetAllRegistriesParamsScopeDescendants GetAllRegistriesParamsScope = "descendants"
	GetAllRegistriesParamsScopeNone        GetAllRegistriesParamsScope = "none"
)

// AccessKeySecretKey defines model for AccessKeySecretKey.
type AccessKeySecretKey struct {
	AccessKey                 *string `json:"accessKey,omitempty"`
	AccessKeySecretIdentifier *string `json:"accessKeySecretIdentifier,omitempty"`
	AccessKeySecretSpaceId    *int64  `json:"accessKeySecretSpaceId,omitempty"`
	AccessKeySecretSpacePath  *string `json:"accessKeySecretSpacePath,omitempty"`
	SecretKeyIdentifier       string  `json:"secretKeyIdentifier"`
	SecretKeySpaceId          *int64  `json:"secretKeySpaceId,omitempty"`
	SecretKeySpacePath        *string `json:"secretKeySpacePath,omitempty"`
}

// Anonymous defines model for Anonymous.
type Anonymous = interface{}

// ArtifactEntityMetadata Artifact Entity Metadata
type ArtifactEntityMetadata map[string]interface{}

// ArtifactType refers to artifact type
type ArtifactType string

// ArtifactVersionMetadata Artifact Version Metadata
type ArtifactVersionMetadata struct {
	// ArtifactType refers to artifact type
	ArtifactType *ArtifactType `json:"artifactType,omitempty"`

	// DeletedAt Timestamp in milliseconds when the artifact was soft deleted. Null if not deleted.
	DeletedAt          *string                              `json:"deletedAt,omitempty"`
	DeploymentMetadata *DeploymentMetadata                  `json:"deploymentMetadata,omitempty"`
	DigestCount        *int64                               `json:"digestCount,omitempty"`
	DownloadsCount     *int64                               `json:"downloadsCount,omitempty"`
	FileCount          *int64                               `json:"fileCount,omitempty"`
	FirewallMode       *ArtifactVersionMetadataFirewallMode `json:"firewallMode,omitempty"`
	IsQuarantined      *bool                                `json:"isQuarantined,omitempty"`
	LastModified       *string                              `json:"lastModified,omitempty"`
	LastScannedAt      *string                              `json:"lastScannedAt,omitempty"`

	// Metadata Artifact Entity Metadata
	Metadata *ArtifactEntityMetadata `json:"metadata,omitempty"`
	Name     string                  `json:"name"`

	// PackageType refers to package
	PackageType        PackageType `json:"packageType"`
	PullCommand        *string     `json:"pullCommand,omitempty"`
	QuarantineReason   *string     `json:"quarantineReason,omitempty"`
	RegistryIdentifier string      `json:"registryIdentifier"`
	RegistryPath       string      `json:"registryPath"`

	// RegistryType refers to type of registry i.e virtual or upstream
	RegistryType *RegistryType                      `json:"registryType,omitempty"`
	RegistryUUID string                             `json:"registryUUID"`
	ScanId       *string                            `json:"scanId,omitempty"`
	ScanStatus   *ArtifactVersionMetadataScanStatus `json:"scanStatus,omitempty"`
	Size         *string                            `json:"size,omitempty"`
	Uuid         string                             `json:"uuid"`
}

// ArtifactVersionMetadataFirewallMode defines model for ArtifactVersionMetadata.FirewallMode.
type ArtifactVersionMetadataFirewallMode string

// ArtifactVersionMetadataScanStatus defines model for ArtifactVersionMetadata.ScanStatus.
type ArtifactVersionMetadataScanStatus string

// AuthType Authentication type
type AuthType string

// CleanupPolicy Cleanup Policy for Harness Artifact Registries
type CleanupPolicy struct {
	ExpireDays    *int      `json:"expireDays,omitempty"`
	Name          *string   `json:"name,omitempty"`
	PackagePrefix *[]string `json:"packagePrefix,omitempty"`
	VersionPrefix *[]string `json:"versionPrefix,omitempty"`
}

// DeploymentMetadata defines model for DeploymentMetadata.
type DeploymentMetadata struct {
	NonProdEnvCount int `json:"nonProdEnvCount"`
	ProdEnvCount    int `json:"prodEnvCount"`
}

// Error Standard error response with code, message and optional details
type Error struct {
	// Code The HTTP error code
	Code string `json:"code"`

	// Details Additional context and details about the error.
	// May include field-specific validation errors or debugging information.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error message explaining what went wrong
	Message string `json:"message"`
}

// FileDetail File Detail
type FileDetail struct {
	Checksums       []string `json:"checksums"`
	CreatedAt       string   `json:"createdAt"`
	DownloadCommand string   `json:"downloadCommand"`
	Name            string   `json:"name"`
	Path            string   `json:"path"`
	Size            string   `json:"size"`
}

// ListArtifactVersion A list of Artifact versions
type ListArtifactVersion struct {
	// ArtifactVersions A list of Artifact versions
	ArtifactVersions *[]ArtifactVersionMetadata `json:"artifactVersions,omitempty"`

	// ItemCount The total number of items
	ItemCount *int64 `json:"itemCount,omitempty"`

	// PageCount The total number of pages
	PageCount *int64 `json:"pageCount,omitempty"`

	// PageIndex The current page
	PageIndex *int64 `json:"pageIndex,omitempty"`

	// PageSize The number of items per page
	PageSize *int `json:"pageSize,omitempty"`
}

// ListFileDetail A list of Harness Artifact Files
type ListFileDetail struct {
	// Files A list of Harness Artifact Files
	Files []FileDetail `json:"files"`

	// ItemCount The total number of items
	ItemCount *int64 `json:"itemCount,omitempty"`

	// PageCount The total number of pages
	PageCount *int64 `json:"pageCount,omitempty"`

	// PageIndex The current page
	PageIndex *int64 `json:"pageIndex,omitempty"`

	// PageSize The number of items per page
	PageSize *int `json:"pageSize,omitempty"`
}

// ListRegistry A list of Harness Artifact Registries
type ListRegistry struct {
	// ItemCount The total number of items
	ItemCount *int64 `json:"itemCount,omitempty"`

	// Meta Metadata about the list response
	Meta Meta `json:"meta"`

	// PageCount The total number of pages
	PageCount *int64 `json:"pageCount,omitempty"`

	// PageIndex The current page
	PageIndex *int64 `json:"pageIndex,omitempty"`

	// PageSize The number of items per page
	PageSize *int `json:"pageSize,omitempty"`

	// Registries A list of Harness Artifact Registries
	Registries []RegistryMetadata `json:"registries"`
}

// ListRegistryArtifact A list of Artifacts
type ListRegistryArtifact struct {
	// Artifacts A list of Artifact
	Artifacts []RegistryArtifactMetadata `json:"artifacts"`

	// ItemCount The total number of items
	ItemCount *int64 `json:"itemCount,omitempty"`

	// PageCount The total number of pages
	PageCount *int64 `json:"pageCount,omitempty"`

	// PageIndex The current page
	PageIndex *int64 `json:"pageIndex,omitempty"`

	// PageSize The number of items per page
	PageSize *int `json:"pageSize,omitempty"`
}

// Meta Metadata about the list response
type Meta struct {
	// ActiveCount Count of active (non-deleted) entities
	ActiveCount int64 `json:"activeCount"`

	// DeletedCount Count of soft-deleted entities
	DeletedCount int64 `json:"deletedCount"`
}

// PackageType refers to package
type PackageType string

// Registry Harness Artifact Registry
type Registry struct {
	AllowedPattern *[]string        `json:"allowedPattern,omitempty"`
	BlockedPattern *[]string        `json:"blockedPattern,omitempty"`
	CleanupPolicy  *[]CleanupPolicy `json:"cleanupPolicy,omitempty"`

	// Config SubConfig specific for Virtual or Upstream Registry
	Config    *RegistryConfig `json:"config,omitempty"`
	CreatedAt *string         `json:"createdAt,omitempty"`

	// DeletedAt Timestamp in milliseconds when the artifact was soft deleted. Null if not deleted.
	DeletedAt   *string   `json:"deletedAt,omitempty"`
	Description *string   `json:"description,omitempty"`
	Identifier  string    `json:"identifier"`
	IsPublic    bool      `json:"isPublic"`
	Labels      *[]string `json:"labels,omitempty"`
	ModifiedAt  *string   `json:"modifiedAt,omitempty"`

	// PackageType refers to package
	PackageType PackageType `json:"packageType"`
	PolicyRefs  *[]string   `json:"policyRefs,omitempty"`
	Scanners    *[]Scanner  `json:"scanners,omitempty"`
	Url         string      `json:"url"`
	Uuid        string      `json:"uuid"`
}

// RegistryArtifactMetadata Artifact Metadata
type RegistryArtifactMetadata struct {
	// ArtifactType refers to artifact type
	ArtifactType *ArtifactType `json:"artifactType,omitempty"`

	// DeletedAt Timestamp in milliseconds when the registry was soft-deleted
	DeletedAt      *string `json:"deletedAt,omitempty"`
	DownloadsCount *int64  `json:"downloadsCount,omitempty"`

	// IsDeleted True if the registry is soft-deleted
	IsDeleted     bool      `json:"isDeleted"`
	IsPublic      bool      `json:"isPublic"`
	IsQuarantined *bool     `json:"isQuarantined,omitempty"`
	Labels        *[]string `json:"labels,omitempty"`
	LastModified  *string   `json:"lastModified,omitempty"`
	LatestVersion string    `json:"latestVersion"`
	Name          string    `json:"name"`

	// PackageType refers to package
	PackageType        PackageType `json:"packageType"`
	RegistryIdentifier string      `json:"registryIdentifier"`
	RegistryPath       string      `json:"registryPath"`
	RegistryUUID       string      `json:"registryUUID"`
	Uuid               string      `json:"uuid"`
}

// RegistryConfig SubConfig specific for Virtual or Upstream Registry
type RegistryConfig struct {
	// Type refers to type of registry i.e virtual or upstream
	Type  RegistryType `json:"type"`
	union json.RawMessage
}

// RegistryMetadata Harness Artifact Registry Metadata
type RegistryMetadata struct {
	ArtifactsCount *int64 `json:"artifactsCount,omitempty"`

	// DeletedAt Timestamp in milliseconds when the registry was soft-deleted
	DeletedAt      *string `json:"deletedAt,omitempty"`
	Description    *string `json:"description,omitempty"`
	DownloadsCount *int64  `json:"downloadsCount,omitempty"`
	Identifier     string  `json:"identifier"`

	// IsDeleted True if the registry is soft-deleted
	IsDeleted    bool    `json:"isDeleted"`
	IsPublic     bool    `json:"isPublic"`
	LastModified *string `json:"lastModified,omitempty"`

	// PackageType refers to package
	PackageType  PackageType `json:"packageType"`
	Path         *string     `json:"path,omitempty"`
	RegistrySize *string     `json:"registrySize,omitempty"`

	// Type refers to type of registry i.e virtual or upstream
	Type RegistryType `json:"type"`
	Url  string       `json:"url"`
	Uuid string       `json:"uuid"`
}

// RegistryType refers to type of registry i.e virtual or upstream
type RegistryType string

// Scanner Scanner for Harness Artifact Registries
type Scanner struct {
	Name *ScannerName `json:"name,omitempty"`
}

// ScannerName defines model for Scanner.Name.
type ScannerName string

// Status Request processing status indicator
type Status string

// UpstreamConfig Configuration for Harness Artifact UpstreamProxies
type UpstreamConfig struct {
	Auth *UpstreamConfig_Auth `json:"auth,omitempty"`

	// AuthType Authentication type
	AuthType AuthType `json:"authType"`

	// FirewallMode Firewall mode applied to an upstream proxy.
	FirewallMode *UpstreamProxyConfigFirewallMode `json:"firewallMode,omitempty"`

	// RemoteUrlSuffix Optional path suffix appended to the remote URL for this registry. For Python upstreams, this allows overriding the default `/simple` path used for PyPI-compatible indexes. Leading and trailing slashes are not required and will be normalized.
	RemoteUrlSuffix *string               `json:"remoteUrlSuffix,omitempty"`
	Source          *UpstreamConfigSource `json:"source,omitempty"`
	Url             *string               `json:"url,omitempty"`
}

// UpstreamConfig_Auth defines model for UpstreamConfig.Auth.
type UpstreamConfig_Auth struct {
	union json.RawMessage
}

// UpstreamConfigSource defines model for UpstreamConfig.Source.
type UpstreamConfigSource string

// UpstreamProxyConfigFirewallMode Firewall mode applied to an upstream proxy.
type UpstreamProxyConfigFirewallMode string

// UserPassword defines model for UserPassword.
type UserPassword struct {
	SecretIdentifier *string `json:"secretIdentifier,omitempty"`
	SecretSpaceId    *int    `json:"secretSpaceId,omitempty"`
	SecretSpacePath  *string `json:"secretSpacePath,omitempty"`
	UserName         string  `json:"userName"`
}

// VirtualConfig Configuration for Harness Virtual Artifact Registries
type VirtualConfig struct {
	UpstreamProxies *[]string `json:"upstreamProxies,omitempty"`
}

// LabelsParam defines model for LabelsParam.
type LabelsParam = []string

// RegistryTypeParam defines model for RegistryTypeParam.
type RegistryTypeParam string

// ArtifactPathParam defines model for artifactPathParam.
type ArtifactPathParam = string

// ArtifactTypeParam defines model for artifactTypeParam.
type ArtifactTypeParam string

// PackageTypeParam defines model for packageTypeParam.
type PackageTypeParam = []string

// PageNumber defines model for pageNumber.
type PageNumber = int64

// PageSize defines model for pageSize.
type PageSize = int64

// RecursiveParam defines model for recursiveParam.
type RecursiveParam = bool

// RegistryRefPathParam defines model for registryRefPathParam.
type RegistryRefPathParam = string

// ScopeParam defines model for scopeParam.
type ScopeParam string

// SearchTerm defines model for searchTerm.
type SearchTerm = string

// SortField defines model for sortField.
type SortField = string

// SortOrder defines model for sortOrder.
type SortOrder = string

// SpaceRefPathParam defines model for spaceRefPathParam.
type SpaceRefPathParam = string

// VersionPathParam defines model for versionPathParam.
type VersionPathParam = string

// BadRequest Standard error response with code, message and optional details
type BadRequest = Error

// FileDetailResponse defines model for FileDetailResponse.
type FileDetailResponse struct {
	// Data A list of Harness Artifact Files
	Data ListFileDetail `json:"data"`

	// Status Request processing status indicator
	Status Status `json:"status"`
}

// InternalServerError Standard error response with code, message and optional details
type InternalServerError = Error

// ListArtifactVersionResponse defines model for ListArtifactVersionResponse.
type ListArtifactVersionResponse struct {
	// Data A list of Artifact versions
	Data ListArtifactVersion `json:"data"`

	// Status Request processing status indicator
	Status Status `json:"status"`
}

// ListRegistryArtifactResponse defines model for ListRegistryArtifactResponse.
type ListRegistryArtifactResponse struct {
	// Data A list of Artifacts
	Data ListRegistryArtifact `json:"data"`

	// Status Request processing status indicator
	Status Status `json:"status"`
}

// ListRegistryResponse defines model for ListRegistryResponse.
type ListRegistryResponse struct {
	// Data A list of Harness Artifact Registries
	Data ListRegistry `json:"data"`

	// Status Request processing status indicator
	Status Status `json:"status"`
}

// NotFound Standard error response with code, message and optional details
type NotFound = Error

// RegistryResponse defines model for RegistryResponse.
type RegistryResponse struct {
	// Data Harness Artifact Registry
	Data Registry `json:"data"`

	// Status Request processing status indicator
	Status Status `json:"status"`
}

// Unauthenticated Standard error response with code, message and optional details
type Unauthenticated = Error

// Unauthorized Standard error response with code, message and optional details
type Unauthorized = Error

// GetArtifactFilesParams defines parameters for GetArtifactFiles.
type GetArtifactFilesParams struct {
	// ArtifactType artifact type.
	ArtifactType *GetArtifactFilesParamsArtifactType `form:"artifact_type,omitempty" json:"artifact_type,omitempty"`

	// Page Current page number
	Page *PageNumber `form:"page,omitempty" json:"page,omitempty"`

	// Size Number of items per page
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`

	// SortOrder sortOrder
	SortOrder *SortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`

	// SortField sortField
	SortField *SortField `form:"sort_field,omitempty" json:"sort_field,omitempty"`

	// SearchTerm search Term.
	SearchTerm *SearchTerm `form:"search_term,omitempty" json:"search_term,omitempty"`
}

// GetArtifactFilesParamsArtifactType defines parameters for GetArtifactFiles.
type GetArtifactFilesParamsArtifactType string

// GetAllArtifactVersionsParams defines parameters for GetAllArtifactVersions.
type GetAllArtifactVersionsParams struct {
	// ArtifactType artifact type.
	ArtifactType *GetAllArtifactVersionsParamsArtifactType `form:"artifact_type,omitempty" json:"artifact_type,omitempty"`

	// Page Current page number
	Page *PageNumber `form:"page,omitempty" json:"page,omitempty"`

	// Size Number of items per page
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`

	// SortOrder sortOrder
	SortOrder *SortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`

	// SortField sortField
	SortField *SortField `form:"sort_field,omitempty" json:"sort_field,omitempty"`

	// SearchTerm search Term.
	SearchTerm *SearchTerm `form:"search_term,omitempty" json:"search_term,omitempty"`
}

// GetAllArtifactVersionsParamsArtifactType defines parameters for GetAllArtifactVersions.
type GetAllArtifactVersionsParamsArtifactType string

// GetAllArtifactsByRegistryParams defines parameters for GetAllArtifactsByRegistry.
type GetAllArtifactsByRegistryParams struct {
	// Label Label.
	Label *LabelsParam `form:"label,omitempty" json:"label,omitempty"`

	// Page Current page number
	Page *PageNumber `form:"page,omitempty" json:"page,omitempty"`

	// Size Number of items per page
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`

	// SortOrder sortOrder
	SortOrder *SortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`

	// SortField sortField
	SortField *SortField `form:"sort_field,omitempty" json:"sort_field,omitempty"`

	// SearchTerm search Term.
	SearchTerm *SearchTerm `form:"search_term,omitempty" json:"search_term,omitempty"`

	// ArtifactType artifact type.
	ArtifactType *GetAllArtifactsByRegistryParamsArtifactType `form:"artifact_type,omitempty" json:"artifact_type,omitempty"`
}

// GetAllArtifactsByRegistryParamsArtifactType defines parameters for GetAllArtifactsByRegistry.
type GetAllArtifactsByRegistryParamsArtifactType string

// GetAllRegistriesParams defines parameters for GetAllRegistries.
type GetAllRegistriesParams struct {
	// PackageType Registry Package Type
	PackageType *PackageTypeParam `form:"package_type,omitempty" json:"package_type,omitempty"`

	// Type Registry Type
	Type *GetAllRegistriesParamsType `form:"type,omitempty" json:"type,omitempty"`

	// Page Current page number
	Page *PageNumber `form:"page,omitempty" json:"page,omitempty"`

	// Size Number of items per page
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`

	// SortOrder sortOrder
	SortOrder *SortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`

	// SortField sortField
	SortField *SortField `form:"sort_field,omitempty" json:"sort_field,omitempty"`

	// SearchTerm search Term.
	SearchTerm *SearchTerm `form:"search_term,omitempty" json:"search_term,omitempty"`

	// Recursive Whether to list registries recursively.
	//
	// **Deprecated.** Use the new `scope` parameter.
	//
	// * `recursive=true`  → `scope=ancestors`
	// * `recursive=false` → `scope=none`
	Recursive *RecursiveParam `form:"recursive,omitempty" json:"recursive,omitempty"`

	// Scope **Scope of registries to list**
	// * **none** – current space only (default)   * **ancestors** – current space **plus** all parent spaces   * **descendants** – current space **plus** all child spaces
	// If omitted, `none` is assumed.
	Scope *GetAllRegistriesParamsScope `form:"scope,omitempty" json:"scope,omitempty"`
}

// GetAllRegistriesParamsType defines parameters for GetAllRegistries.
type GetAllRegistriesParamsType string

// GetAllRegistriesParamsScope defines parameters for GetAllRegistries.
type GetAllRegistriesParamsScope string

// AsVirtualConfig returns the union data inside the RegistryConfig as a VirtualConfig
func (t RegistryConfig) AsVirtualConfig() (VirtualConfig, error) {
	var body VirtualConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVirtualConfig overwrites any union data inside the RegistryConfig as the provided VirtualConfig
func (t *RegistryConfig) FromVirtualConfig(v VirtualConfig) error {
	t.Type = "VIRTUAL"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVirtualConfig performs a merge with any union data inside the RegistryConfig, using the provided VirtualConfig
func (t *RegistryConfig) MergeVirtualConfig(v VirtualConfig) error {
	t.Type = "VIRTUAL"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUpstreamConfig returns the union data inside the RegistryConfig as a UpstreamConfig
func (t RegistryConfig) AsUpstreamConfig() (UpstreamConfig, error) {
	var body UpstreamConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpstreamConfig overwrites any union data inside the RegistryConfig as the provided UpstreamConfig
func (t *RegistryConfig) FromUpstreamConfig(v UpstreamConfig) error {
	t.Type = "UPSTREAM"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUpstreamConfig performs a merge with any union data inside the RegistryConfig, using the provided UpstreamConfig
func (t *RegistryConfig) MergeUpstreamConfig(v UpstreamConfig) error {
	t.Type = "UPSTREAM"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RegistryConfig) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t RegistryConfig) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "UPSTREAM":
		return t.AsUpstreamConfig()
	case "VIRTUAL":
		return t.AsVirtualConfig()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t RegistryConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["type"], err = json.Marshal(t.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *RegistryConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}

	return err
}

// AsUserPassword returns the union data inside the UpstreamConfig_Auth as a UserPassword
func (t UpstreamConfig_Auth) AsUserPassword() (UserPassword, error) {
	var body UserPassword
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserPassword overwrites any union data inside the UpstreamConfig_Auth as the provided UserPassword
func (t *UpstreamConfig_Auth) FromUserPassword(v UserPassword) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserPassword performs a merge with any union data inside the UpstreamConfig_Auth, using the provided UserPassword
func (t *UpstreamConfig_Auth) MergeUserPassword(v UserPassword) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAnonymous returns the union data inside the UpstreamConfig_Auth as a Anonymous
func (t UpstreamConfig_Auth) AsAnonymous() (Anonymous, error) {
	var body Anonymous
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnonymous overwrites any union data inside the UpstreamConfig_Auth as the provided Anonymous
func (t *UpstreamConfig_Auth) FromAnonymous(v Anonymous) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnonymous performs a merge with any union data inside the UpstreamConfig_Auth, using the provided Anonymous
func (t *UpstreamConfig_Auth) MergeAnonymous(v Anonymous) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAccessKeySecretKey returns the union data inside the UpstreamConfig_Auth as a AccessKeySecretKey
func (t UpstreamConfig_Auth) AsAccessKeySecretKey() (AccessKeySecretKey, error) {
	var body AccessKeySecretKey
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAccessKeySecretKey overwrites any union data inside the UpstreamConfig_Auth as the provided AccessKeySecretKey
func (t *UpstreamConfig_Auth) FromAccessKeySecretKey(v AccessKeySecretKey) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAccessKeySecretKey performs a merge with any union data inside the UpstreamConfig_Auth, using the provided AccessKeySecretKey
func (t *UpstreamConfig_Auth) MergeAccessKeySecretKey(v AccessKeySecretKey) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UpstreamConfig_Auth) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UpstreamConfig_Auth) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetRegistry request
	GetRegistry(ctx context.Context, registryRef RegistryRefPathParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetArtifactFiles request
	GetArtifactFiles(ctx context.Context, registryRef RegistryRefPathParam, artifact ArtifactPathParam, version VersionPathParam, params *GetArtifactFilesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAllArtifactVersions request
	GetAllArtifactVersions(ctx context.Context, registryRef RegistryRefPathParam, artifact ArtifactPathParam, params *GetAllArtifactVersionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAllArtifactsByRegistry request
	GetAllArtifactsByRegistry(ctx context.Context, registryRef RegistryRefPathParam, params *GetAllArtifactsByRegistryParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAllRegistries request
	GetAllRegistries(ctx context.Context, spaceRef SpaceRefPathParam, params *GetAllRegistriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetRegistry(ctx context.Context, registryRef RegistryRefPathParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRegistryRequest(c.Server, registryRef)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetArtifactFiles(ctx context.Context, registryRef RegistryRefPathParam, artifact ArtifactPathParam, version VersionPathParam, params *GetArtifactFilesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetArtifactFilesRequest(c.Server, registryRef, artifact, version, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAllArtifactVersions(ctx context.Context, registryRef RegistryRefPathParam, artifact ArtifactPathParam, params *GetAllArtifactVersionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAllArtifactVersionsRequest(c.Server, registryRef, artifact, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAllArtifactsByRegistry(ctx context.Context, registryRef RegistryRefPathParam, params *GetAllArtifactsByRegistryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAllArtifactsByRegistryRequest(c.Server, registryRef, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAllRegistries(ctx context.Context, spaceRef SpaceRefPathParam, params *GetAllRegistriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAllRegistriesRequest(c.Server, spaceRef, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetRegistryRequest generates requests for GetRegistry
func NewGetRegistryRequest(server string, registryRef RegistryRefPathParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "registry_ref", runtime.ParamLocationPath, registryRef)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/registry/%s/+", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetArtifactFilesRequest generates requests for GetArtifactFiles
func NewGetArtifactFilesRequest(server string, registryRef RegistryRefPathParam, artifact ArtifactPathParam, version VersionPathParam, params *GetArtifactFilesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "registry_ref", runtime.ParamLocationPath, registryRef)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "artifact", runtime.ParamLocationPath, artifact)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/registry/%s/+/artifact/%s/+/version/%s/files", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ArtifactType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "artifact_type", runtime.ParamLocationQuery, *params.ArtifactType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Size != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "size", runtime.ParamLocationQuery, *params.Size); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortOrder != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_order", runtime.ParamLocationQuery, *params.SortOrder); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortField != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_field", runtime.ParamLocationQuery, *params.SortField); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SearchTerm != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "search_term", runtime.ParamLocationQuery, *params.SearchTerm); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAllArtifactVersionsRequest generates requests for GetAllArtifactVersions
func NewGetAllArtifactVersionsRequest(server string, registryRef RegistryRefPathParam, artifact ArtifactPathParam, params *GetAllArtifactVersionsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "registry_ref", runtime.ParamLocationPath, registryRef)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "artifact", runtime.ParamLocationPath, artifact)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/registry/%s/+/artifact/%s/+/versions", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ArtifactType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "artifact_type", runtime.ParamLocationQuery, *params.ArtifactType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Size != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "size", runtime.ParamLocationQuery, *params.Size); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortOrder != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_order", runtime.ParamLocationQuery, *params.SortOrder); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortField != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_field", runtime.ParamLocationQuery, *params.SortField); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SearchTerm != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "search_term", runtime.ParamLocationQuery, *params.SearchTerm); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAllArtifactsByRegistryRequest generates requests for GetAllArtifactsByRegistry
func NewGetAllArtifactsByRegistryRequest(server string, registryRef RegistryRefPathParam, params *GetAllArtifactsByRegistryParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "registry_ref", runtime.ParamLocationPath, registryRef)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/registry/%s/+/artifacts", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Label != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "label", runtime.ParamLocationQuery, *params.Label); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Size != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "size", runtime.ParamLocationQuery, *params.Size); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortOrder != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_order", runtime.ParamLocationQuery, *params.SortOrder); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortField != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_field", runtime.ParamLocationQuery, *params.SortField); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SearchTerm != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "search_term", runtime.ParamLocationQuery, *params.SearchTerm); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ArtifactType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "artifact_type", runtime.ParamLocationQuery, *params.ArtifactType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAllRegistriesRequest generates requests for GetAllRegistries
func NewGetAllRegistriesRequest(server string, spaceRef SpaceRefPathParam, params *GetAllRegistriesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "space_ref", runtime.ParamLocationPath, spaceRef)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/spaces/%s/+/registries", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.PackageType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "package_type", runtime.ParamLocationQuery, *params.PackageType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, *params.Type); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Size != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "size", runtime.ParamLocationQuery, *params.Size); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortOrder != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_order", runtime.ParamLocationQuery, *params.SortOrder); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortField != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_field", runtime.ParamLocationQuery, *params.SortField); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SearchTerm != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "search_term", runtime.ParamLocationQuery, *params.SearchTerm); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Recursive != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "recursive", runtime.ParamLocationQuery, *params.Recursive); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Scope != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "scope", runtime.ParamLocationQuery, *params.Scope); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetRegistryWithResponse request
	GetRegistryWithResponse(ctx context.Context, registryRef RegistryRefPathParam, reqEditors ...RequestEditorFn) (*GetRegistryResponse, error)

	// GetArtifactFilesWithResponse request
	GetArtifactFilesWithResponse(ctx context.Context, registryRef RegistryRefPathParam, artifact ArtifactPathParam, version VersionPathParam, params *GetArtifactFilesParams, reqEditors ...RequestEditorFn) (*GetArtifactFilesResponse, error)

	// GetAllArtifactVersionsWithResponse request
	GetAllArtifactVersionsWithResponse(ctx context.Context, registryRef RegistryRefPathParam, artifact ArtifactPathParam, params *GetAllArtifactVersionsParams, reqEditors ...RequestEditorFn) (*GetAllArtifactVersionsResponse, error)

	// GetAllArtifactsByRegistryWithResponse request
	GetAllArtifactsByRegistryWithResponse(ctx context.Context, registryRef RegistryRefPathParam, params *GetAllArtifactsByRegistryParams, reqEditors ...RequestEditorFn) (*GetAllArtifactsByRegistryResponse, error)

	// GetAllRegistriesWithResponse request
	GetAllRegistriesWithResponse(ctx context.Context, spaceRef SpaceRefPathParam, params *GetAllRegistriesParams, reqEditors ...RequestEditorFn) (*GetAllRegistriesResponse, error)
}

type GetRegistryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RegistryResponse
	JSON400      *BadRequest
	JSON401      *Unauthenticated
	JSON403      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetRegistryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRegistryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetArtifactFilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FileDetailResponse
	JSON400      *BadRequest
	JSON401      *Unauthenticated
	JSON403      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetArtifactFilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetArtifactFilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAllArtifactVersionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListArtifactVersionResponse
	JSON400      *BadRequest
	JSON401      *Unauthenticated
	JSON403      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetAllArtifactVersionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAllArtifactVersionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAllArtifactsByRegistryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListRegistryArtifactResponse
	JSON400      *BadRequest
	JSON401      *Unauthenticated
	JSON403      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetAllArtifactsByRegistryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAllArtifactsByRegistryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAllRegistriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListRegistryResponse
	JSON400      *BadRequest
	JSON401      *Unauthenticated
	JSON403      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetAllRegistriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAllRegistriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetRegistryWithResponse request returning *GetRegistryResponse
func (c *ClientWithResponses) GetRegistryWithResponse(ctx context.Context, registryRef RegistryRefPathParam, reqEditors ...RequestEditorFn) (*GetRegistryResponse, error) {
	rsp, err := c.GetRegistry(ctx, registryRef, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRegistryResponse(rsp)
}

// GetArtifactFilesWithResponse request returning *GetArtifactFilesResponse
func (c *ClientWithResponses) GetArtifactFilesWithResponse(ctx context.Context, registryRef RegistryRefPathParam, artifact ArtifactPathParam, version VersionPathParam, params *GetArtifactFilesParams, reqEditors ...RequestEditorFn) (*GetArtifactFilesResponse, error) {
	rsp, err := c.GetArtifactFiles(ctx, registryRef, artifact, version, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetArtifactFilesResponse(rsp)
}

// GetAllArtifactVersionsWithResponse request returning *GetAllArtifactVersionsResponse
func (c *ClientWithResponses) GetAllArtifactVersionsWithResponse(ctx context.Context, registryRef RegistryRefPathParam, artifact ArtifactPathParam, params *GetAllArtifactVersionsParams, reqEditors ...RequestEditorFn) (*GetAllArtifactVersionsResponse, error) {
	rsp, err := c.GetAllArtifactVersions(ctx, registryRef, artifact, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAllArtifactVersionsResponse(rsp)
}

// GetAllArtifactsByRegistryWithResponse request returning *GetAllArtifactsByRegistryResponse
func (c *ClientWithResponses) GetAllArtifactsByRegistryWithResponse(ctx context.Context, registryRef RegistryRefPathParam, params *GetAllArtifactsByRegistryParams, reqEditors ...RequestEditorFn) (*GetAllArtifactsByRegistryResponse, error) {
	rsp, err := c.GetAllArtifactsByRegistry(ctx, registryRef, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAllArtifactsByRegistryResponse(rsp)
}

// GetAllRegistriesWithResponse request returning *GetAllRegistriesResponse
func (c *ClientWithResponses) GetAllRegistriesWithResponse(ctx context.Context, spaceRef SpaceRefPathParam, params *GetAllRegistriesParams, reqEditors ...RequestEditorFn) (*GetAllRegistriesResponse, error) {
	rsp, err := c.GetAllRegistries(ctx, spaceRef, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAllRegistriesResponse(rsp)
}

// ParseGetRegistryResponse parses an HTTP response from a GetRegistryWithResponse call
func ParseGetRegistryResponse(rsp *http.Response) (*GetRegistryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRegistryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RegistryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetArtifactFilesResponse parses an HTTP response from a GetArtifactFilesWithResponse call
func ParseGetArtifactFilesResponse(rsp *http.Response) (*GetArtifactFilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetArtifactFilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FileDetailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAllArtifactVersionsResponse parses an HTTP response from a GetAllArtifactVersionsWithResponse call
func ParseGetAllArtifactVersionsResponse(rsp *http.Response) (*GetAllArtifactVersionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAllArtifactVersionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListArtifactVersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAllArtifactsByRegistryResponse parses an HTTP response from a GetAllArtifactsByRegistryWithResponse call
func ParseGetAllArtifactsByRegistryResponse(rsp *http.Response) (*GetAllArtifactsByRegistryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAllArtifactsByRegistryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListRegistryArtifactResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAllRegistriesResponse parses an HTTP response from a GetAllRegistriesWithResponse call
func ParseGetAllRegistriesResponse(rsp *http.Response) (*GetAllRegistriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAllRegistriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListRegistryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
