openapi: 3.0.3
info:
    title: Harness Security Test Orchestration API
    description: Read and manage Security Test results.
    version: 1.0.0
servers:
    - url: https://app.harness.io/gateway/sto
    - url: http://127.0.0.1:4000
paths:
    /api/usage:
        get:
            description: Report usage
            operationId: Usage#ReportUsage
            security:
                - jwt_header_Authorization:
                    - core_account_view
            tags:
                - Usage
        x-internal: true
    /api/usage/all-accounts:
        get:
            description: Report usage for all accounts
            operationId: Usage#UsageAllAccounts
            security:
                - jwt_header_Authorization:
                    - sto_internal_use_only
            tags:
                - Usage
        x-internal: true
    /api/v2/accounts/{id}/data:
        delete:
            description: Delete all account data
            operationId: Accounts#DeleteAccountData
            security:
                - jwt_header_Authorization:
                    - sto_internal_use_only
            tags:
                - Accounts
        x-internal: true
    /api/v2/exemptions:
        get:
            tags:
                - Exemptions
            description: List a collection of Exemptions
            operationId: Exemptions#ListExemptions
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_exemption_view
        post:
            tags:
                - Exemptions
            description: Create a new Exemption
            operationId: Exemptions#CreateExemption
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_exemption_create
    /api/v2/exemptions/{id}:
        delete:
            description: Delete an existing Exemption
            operationId: Exemptions#DeleteExemption
            security:
                - jwt_header_Authorization:
                    - sto_exemption_create
            tags:
                - Exemptions
            x-internal: true
        get:
            tags:
                - Exemptions
            description: Find Exemption by ID
            operationId: Exemptions#FindExemptionById
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_exemption_view
        put:
            tags:
                - Exemptions
            description: Update an existing Exemption
            operationId: Exemptions#UpdateExemption
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_exemption_create
    /api/v2/exemptions/{id}/{action}:
        put:
            tags:
                - Exemptions
            description: Approve/reject an existing Exemption
            operationId: Exemptions#ApproveExemption
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_exemption_approve
    /api/v2/exemptions/{id}/promote:
        put:
            tags:
                - Exemptions
            description: Promote an existing Exemption to a higher scope
            operationId: Exemptions#PromoteExemption
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_exemption_approve
    /api/v2/frontend/all-issues/filters:
        get:
            description: Provide list of filters for a projects latest baseline scans
            operationId: Frontend#AllIssuesFilters
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/all-issues/issues:
        get:
            description: Provides a paginated list of issues for a project found in the latest baseline scans
            operationId: Frontend#AllIssuesList
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/all-issues/issues/{issueId}:
        get:
            description: Provides issue details for a project's latest baseline scans
            operationId: Frontend#AllIssuesDetails
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/all-issues/issues/{issueId}/targets/{targetId}:
        get:
            description: Provide list of filters for the latest scans of a baseline
            operationId: Frontend#AllIssuesOccurrenceDetails
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/exemption/{exemptionId}/issue-severity-change:
        get:
            description: Provides the severity change for an issue when approving occurrence level exemption
            operationId: Frontend#IssueSeverityChange
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/exemption/{exemptionId}/targets:
        get:
            description: Returns a list of impacted target details for an exemption id
            operationId: Frontend#ImpactedTargetsForExemption
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/exemptions:
        get:
            description: Provides data needed by the Global Exemptions Security Review page
            operationId: Frontend#GlobalExemptions
            security:
                - jwt_header_Authorization:
                    - sto_exemption_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/expiring-exemptions/{executionId}:
        get:
            description: Returns issue summaries that are going to expire
            operationId: Frontend#ExpiringExemptions
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/issue-counts:
        get:
            description: Returns counts of active Security Issues for one or more Pipeline Executions
            operationId: Frontend#ExecutionIssueCounts
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/issue-exemption/{exemptionId}:
        get:
            description: Returns a specific issue exemption
            operationId: Frontend#IssueForExemption
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/overview/baselines:
        get:
            description: Provides baseline execution data needed by the Overview page
            operationId: Frontend#OverviewBaselines
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/overview/historical-counts:
        get:
            description: Provides historical issue data needed by the Overview page
            operationId: Frontend#OverviewHistoricalCounts
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/pipeline-security/issues:
        get:
            description: Provide issue data needed by the PipelineSecurityView
            operationId: Frontend#PipelineSecurityIssues
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/pipeline-security/steps:
        get:
            description: Provide step data needed by the PipelineSecurityView
            operationId: Frontend#PipelineSecuritySteps
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/security-review:
        get:
            description: Provides data needed by the Security Review page
            operationId: Frontend#SecurityReview
            security:
                - jwt_header_Authorization:
                    - sto_exemption_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/frontend/test-targets:
        get:
            description: Provides data needed by the Test Targets page
            operationId: Frontend#TestTargets
            security:
                - jwt_header_Authorization:
                    - sto_testtarget_view
            tags:
                - Frontend
        x-internal: true
    /api/v2/issues:
        get:
            tags:
                - Issues
            description: List a collection of Security Issues
            operationId: Issues#ListIssues
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
        post:
            tags:
                - Issues
            description: Create a new Security Issue
            operationId: Issues#CreateIssue
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_edit
    /api/v2/issues/{id}:
        delete:
            description: Delete an existing Security Issue
            operationId: Issues#DeleteIssue
            security:
                - jwt_header_Authorization:
                    - sto_issue_delete
            tags:
                - Issues
            x-internal: true
        get:
            tags:
                - Issues
            description: Find Security Issue by ID
            operationId: Issues#FindIssueById
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
        put:
            tags:
                - Issues
            description: Update an existing Security Issue
            operationId: Issues#UpdateIssue
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_edit
    /api/v2/issues/{id}/augment-remediation:
        post:
            tags:
                - Issues
            description: Use AI to augment the remediation steps for this Security Issue
            operationId: Issues#IssuesAugmentRemediation
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
    /api/v2/products:
        get:
            tags:
                - Products
            description: List a collection of Scan Tools
            operationId: Products#ListProducts
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - core_account_view
    /api/v2/products/{id}:
        get:
            tags:
                - Products
            description: Find Scan Tool by ID
            operationId: Products#FindProductById
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - core_account_view
    /api/v2/pull-requests/repositories:
        get:
            operationId: Pull Requests#ListPullRequests
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Pull Requests
        x-internal: true
    /api/v2/pull-requests/repositories/pulls:
        get:
            operationId: Pull Requests#FindPullRequestByID
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Pull Requests
        post:
            description: Use AI to augment the remediation steps for this Security Issue
            operationId: Pull Requests#CreatePullRequest
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Pull Requests
        put:
            description: Use AI to augment the remediation steps for this Security Issue
            operationId: Pull Requests#UpdatePullRequest
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - Pull Requests
        x-internal: true
    /api/v2/pull-requests/repositories/pulls/correlation:
        get:
            description: Determine if a path is correlated to a Pull Request.
            operationId: Pull Requests#GetPullRequestCorrelation
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
            summary: GetPullRequestCorrelation Pull Requests
            tags:
                - Pull Requests
        x-internal: true
    /api/v2/reference-identifiers/{refId}:
        get:
            tags:
                - Reference Identifiers
            description: Reference Identifiers Lookup
            operationId: Reference Identifiers#getByReferenceId
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - core_account_view
    /api/v2/scans:
        get:
            tags:
                - Scans
            description: List a collection of Security Test Scans
            operationId: Scans#ListScans
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_scan_view
        post:
            tags:
                - Scans
            description: Create a new Security Test Scan
            operationId: Scans#CreateScan
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_scan_edit
    /api/v2/scans/{id}:
        delete:
            description: Delete an existing Security Test Scan
            operationId: Scans#DeleteScan
            security:
                - jwt_header_Authorization:
                    - sto_scan_delete
            tags:
                - Scans
            x-internal: true
        get:
            tags:
                - Scans
            description: Find Security Test Scan by ID
            operationId: Scans#FindScanById
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_scan_view
        put:
            tags:
                - Scans
            description: Update an existing Security Test Scan
            operationId: Scans#UpdateScan
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_scan_edit
    /api/v2/scans/{id}/issue/{issueId}:
        get:
            tags:
                - Scans
            description: Returns a scan specific issue
            operationId: Scans#ScanIssue
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
    /api/v2/scans/{id}/issue/{issueId}/occurrences:
        get:
            tags:
                - Scans
            description: Returns occurrences for a scan specific issue
            operationId: Scans#ScanIssueOccurrences
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
    /api/v2/scans/{id}/issues:
        get:
            tags:
                - Scans
            description: List Issues by Scan ID
            operationId: Scans#ScanIssues
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
    /api/v2/scans/{id}/issues/counts:
        get:
            tags:
                - Scans
            description: Returns counts of active Security Issues for a Security Test Scan
            operationId: Scans#ScanIssueCounts
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_issue_view
    /api/v2/sto-data-frontend/all-issues/issues:
        post:
            description: Provides a paginated list of issues for the provided target name and variant combinations
            operationId: STO Data Frontend#AllIssuesList
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            summary: List of issues for selected targets and variants
            tags:
                - STO Data Frontend
        x-internal: true
    /api/v2/sto-data-frontend/artifact-summary:
        post:
            description: Returns counts of active Security Issues for one or more Pipeline Executions
            operationId: STO Data Frontend#ExecutionArtifactSummary
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - STO Data Frontend
        x-internal: true
    /api/v2/sto-data-frontend/execution-summary/{executionId}:
        get:
            description: Returns counts of active Security Issues for a specific Pipeline Executions
            operationId: STO Data Frontend#ExecutionSummary
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - STO Data Frontend
        x-internal: true
    /api/v2/sto-data-frontend/issue-counts:
        post:
            description: Returns counts of active Security Issues for one or more Pipeline Executions
            operationId: STO Data Frontend#ExecutionIssueCounts
            security:
                - jwt_header_Authorization:
                    - sto_issue_view
            tags:
                - STO Data Frontend
        x-internal: true
    /api/v2/system/health:
        get:
            tags:
                - System
            description: Check service health
            operationId: System#health
    /api/v2/system/version:
        get:
            tags:
                - System
            description: Get service version
            operationId: System#version
    /api/v2/targets:
        get:
            tags:
                - Test Targets
            description: List a collection of Test Targets
            operationId: Targets#ListTargets
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_testtarget_view
        post:
            tags:
                - Test Targets
            description: Create a new Test Target
            operationId: Targets#CreateTarget
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_testtarget_edit
    /api/v2/targets/{id}:
        delete:
            description: Delete an existing Test Target
            operationId: Targets#DeleteTarget
            security:
                - jwt_header_Authorization:
                    - sto_testtarget_delete
            tags:
                - Test Targets
            x-internal: true
        get:
            tags:
                - Test Targets
            description: Find Test Target by ID
            operationId: Targets#FindTargetById
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_testtarget_view
        patch:
            tags:
                - Test Targets
            description: Update only certain fields on an existing Test Target
            operationId: Targets#PatchTarget
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_testtarget_edit
        put:
            tags:
                - Test Targets
            description: Update an existing Test Target
            operationId: Targets#UpdateTarget
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_testtarget_edit
    /api/v2/targets/{targetId}/variants:
        get:
            tags:
                - Target Variants
            description: List a collection of Scan Target Variants
            operationId: Target Variants#ListTargetVariants
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_testtarget_view
        post:
            tags:
                - Target Variants
            description: Create a new Scan Target Variant
            operationId: Target Variants#CreateTargetVariant
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_testtarget_edit
    /api/v2/targets/{targetId}/variants/{id}:
        delete:
            description: Delete an existing Scan Target Variant
            operationId: Target Variants#DeleteTargetVariant
            security:
                - jwt_header_Authorization:
                    - sto_testtarget_delete
            tags:
                - Target Variants
            x-internal: true
        get:
            tags:
                - Target Variants
            description: Find Scan Target Variant by ID
            operationId: Target Variants#FindTargetVariantById
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_testtarget_view
        put:
            tags:
                - Target Variants
            description: Update an existing Scan Target Variant
            operationId: Target Variants#UpdateTargetVariant
            security:
                - X-Api-Key_header_X-Api-Key: []
                  jwt_header_Authorization:
                    - sto_testtarget_edit
    /api/v2/token:
        get:
            description: Issue a cross-service token
            operationId: Token#IssueToken
            security:
                - X-Harness-Token_header_X-Harness-Token: []
            tags:
                - Token
        x-internal: true
components:
    securitySchemes:
        X-Api-Key_header_X-Api-Key:
            type: apiKey
            name: X-Api-Key
            in: header
        X-Harness-Token_header_X-Harness-Token:
            type: apiKey
            name: X-Harness-Token
            in: header
        jwt_header_Authorization:
            type: http
            scheme: bearer
tags:
    - name: Accounts
      description: Account Management Operations
    - name: Exemptions
      description: Access and modify Exemptions to Security Issues
    - name: Products
      description: Access Scan Tool information
    - name: Pull Requests
      description: Access and Modify Pull Requests
    - name: System
      description: Unauthenticated support endpoints
    - name: Target Variants
      description: Access and modify Scan Target Variants
    - name: Frontend
      description: Endpoints that power the STO micro-frontend
    - name: Issues
      description: Access and modify Security Issues
    - name: Scans
      description: Access and modify Security Test Scans
    - name: STO Data Frontend
      description: Endpoints that power the other modules micro-frontend with STO data
    - name: Test Targets
      description: Access and modify Scan Targets
    - name: Token
      description: Internal endpoints for cross-service authentication
    - name: Usage
      description: Access Account Usage
    - name: Reference Identifiers
      description: Reference Identifiers Lookup
