use serde::{Deserialize, Serialize};
use std::time::Duration;
use crate::types::{TransportType, LogFormatType};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    // Common fields for both modes
    pub version: String,
    pub read_only: bool,
    pub toolsets: Vec<String>,
    pub enable_modules: Vec<String>,
    pub log_file_path: String,
    pub debug: bool,
    pub enable_license: bool,
    pub output_dir: Option<String>,
    pub log_format: LogFormatType,

    // Server configuration
    pub transport: TransportType,
    pub http_port: u16,
    pub http_path: String,
    pub metrics_port: u16,

    pub internal: bool,
    pub api_key: Option<String>,
    pub base_url: String,
    pub account_id: String,

    // Only used for external mode
    pub default_org_id: Option<String>,
    pub default_project_id: Option<String>,

    // Only used for internal mode
    pub bearer_token: Option<String>,
    pub pipeline_svc_base_url: Option<String>,
    pub pipeline_svc_secret: Option<String>,
    pub ng_manager_base_url: Option<String>,
    pub ng_manager_secret: Option<String>,
    pub chatbot_base_url: Option<String>,
    pub chatbot_secret: Option<String>,
    pub genai_base_url: Option<String>,
    pub genai_secret: Option<String>,
    pub artifact_registry_base_url: Option<String>,
    pub artifact_registry_secret: Option<String>,
    pub nextgen_ce_base_url: Option<String>,
    pub nextgen_ce_secret: Option<String>,
    pub ccm_comm_orch_base_url: Option<String>,
    pub ccm_comm_orch_secret: Option<String>,
    pub idp_svc_base_url: Option<String>,
    pub idp_svc_secret: Option<String>,
    pub mcp_svc_secret: Option<String>,
    pub chaos_manager_svc_base_url: Option<String>,
    pub chaos_manager_svc_secret: Option<String>,
    pub template_svc_base_url: Option<String>,
    pub template_svc_secret: Option<String>,
    pub intelligence_svc_base_url: Option<String>,
    pub intelligence_svc_secret: Option<String>,
    pub code_svc_base_url: Option<String>,
    pub code_svc_secret: Option<String>,
    pub log_svc_base_url: Option<String>,
    pub log_svc_secret: Option<String>,
    pub dashboard_svc_base_url: Option<String>,
    pub dashboard_svc_secret: Option<String>,
    pub scs_svc_secret: Option<String>,
    pub scs_svc_base_url: Option<String>,
    pub sto_svc_secret: Option<String>,
    pub sto_svc_base_url: Option<String>,
    pub sei_svc_base_url: Option<String>,
    pub sei_svc_secret: Option<String>,
    pub audit_svc_base_url: Option<String>,
    pub audit_svc_secret: Option<String>,
    pub dbops_svc_base_url: Option<String>,
    pub dbops_svc_secret: Option<String>,
    pub acl_svc_base_url: Option<String>,
    pub acl_svc_secret: Option<String>,
    pub release_manager_base_url: Option<String>,
    pub release_manager_secret: Option<String>,

    pub license_cache_ttl: Duration,
    pub license_cache_clean_interval: Duration,
}


impl Default for Config {
    fn default() -> Self {
        Self {
            version: env!("CARGO_PKG_VERSION").to_string(),
            read_only: false,
            toolsets: vec!["default".to_string()],
            enable_modules: vec![],
            log_file_path: "harness-mcp.log".to_string(),
            debug: false,
            enable_license: false,
            output_dir: None,
            log_format: LogFormatType::Text,
            transport: TransportType::Stdio,
            http_port: 8080,
            http_path: "/mcp".to_string(),
            metrics_port: 8889,
            internal: false,
            api_key: None,
            base_url: "https://app.harness.io".to_string(),
            account_id: String::new(),
            default_org_id: None,
            default_project_id: None,
            bearer_token: None,
            pipeline_svc_base_url: None,
            pipeline_svc_secret: None,
            ng_manager_base_url: None,
            ng_manager_secret: None,
            chatbot_base_url: None,
            chatbot_secret: None,
            genai_base_url: None,
            genai_secret: None,
            artifact_registry_base_url: None,
            artifact_registry_secret: None,
            nextgen_ce_base_url: None,
            nextgen_ce_secret: None,
            ccm_comm_orch_base_url: None,
            ccm_comm_orch_secret: None,
            idp_svc_base_url: None,
            idp_svc_secret: None,
            mcp_svc_secret: None,
            chaos_manager_svc_base_url: None,
            chaos_manager_svc_secret: None,
            template_svc_base_url: None,
            template_svc_secret: None,
            intelligence_svc_base_url: None,
            intelligence_svc_secret: None,
            code_svc_base_url: None,
            code_svc_secret: None,
            log_svc_base_url: None,
            log_svc_secret: None,
            dashboard_svc_base_url: None,
            dashboard_svc_secret: None,
            scs_svc_secret: None,
            scs_svc_base_url: None,
            sto_svc_secret: None,
            sto_svc_base_url: None,
            sei_svc_base_url: None,
            sei_svc_secret: None,
            audit_svc_base_url: None,
            audit_svc_secret: None,
            dbops_svc_base_url: None,
            dbops_svc_secret: None,
            acl_svc_base_url: None,
            acl_svc_secret: None,
            release_manager_base_url: None,
            release_manager_secret: None,
            license_cache_ttl: Duration::from_secs(30 * 60), // 30 minutes
            license_cache_clean_interval: Duration::from_secs(5 * 60), // 5 minutes
        }
    }
}

#[cfg(test)]
mod tests;